# Generated by Django 5.0.3 on 2024-03-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_remove_restaurante_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
